### ISSUE TITLE
Schema lacks "description" field of presets

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/manifest-schema#12]
https://github.com/ScratchAddons/ScratchAddons/blob/master/addons/editor-theme3/addon.json

This manifest should follow the schema, but it fails because it doesn't expect presets to have descriptions.
Iirc, this property has been supported since v1.2.0, Oct ~25

**Comment by Hans5958** [comment]
Weird that ZenithKnight didn't add that on that PR.
