### ISSUE TITLE
Localization (l10n) changes

### ISSUE THREAD

**Issue by Hans5958** [ScratchAddons/manifest-schema#14]
Hey guys, please list things that needs to get done with the schema that are related to the localization implementation.

@apple502j @WorldLanguages

**Comment by apple502j** [comment]
- `l10n`: optional boolean indicating if l10n is loaded
- `settings`: `potentialValues` can be array of string (for compatibility) or array of object with `id` and `name` key, both string

**Comment by Hans5958** [comment]
Is that it?

**Comment by WorldLanguages** [comment]
@Hans5958 Yes. You might want to include localization files in the schema, if you wish, but that's it for addon.json, as you requested and I agreed.

**Comment by Hans5958** [comment]
> You might want to include localization files in the schema, if you wish

Um, you don't do that on those.

By the way, remember that you said that "there won't be any other schema in the future?"
