### ISSUE TITLE
New setting type: integer

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/manifest-schema#16]
Optional properties: `min` (integer), `max` (integer). If min is not specified, the settings page will consider -Infinity as the minimum, and viceversa with the maximum.
A setting of type `integer` with min=0 and no max works exactly like a setting of type `positive_integer`.

**Comment by Hans5958** [comment]
Sorry for the long-time response. I finally had time to implement this. Actually, it is not possble to make the default values as infinities, but at least I can check it if it is a number.

Probably next time we should merge `integer` and `positive_integer` into one.
