### ISSUE TITLE
Support potential_values

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/manifest-schema#3]
See https://github.com/ScratchAddons/ScratchAddons/wiki/The-addon-manifest-(addon.json)#declare-optionssettings-optional

**Comment by Hans5958** [comment]
This is weird. I already supported it by adding an if statement if someone set the type as the "select" value. I will test it again just in case.

**Comment by WorldLanguages** [comment]
Lol I forgot to say "in userscripts as well as userstyles" sorry
