### ISSUE TITLE
New properties: injectAsStyleElt, updateUserstylesOnSettingsChange

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/manifest-schema#32]
dynamicDisable (boolean)
Indicates whether the addon's scripts should be considered disabled when disabled as the page is running. Defaults to false.

dynamicEnable (boolean)
Indicates whether the addon's scripts should be considered enabled when enabled as the page is running. Defaults to false.

injectAsStyleElt (boolean)
Indicates whether the addon's userstyles should be injected as style elements rather than link elements. Defaults to false.

updateUserstylesOnSettingsChange (boolean)
Indicates whether the addon's userstyles should be removed and rematched to the new settings. Defaults to false.

**Comment by Hans5958** [comment]
One issue for property, please.

#28, #33, #34, #35

Also, examples, please.
