### ISSUE TITLE
New setting type: table

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/manifest-schema#40]
ScratchAddons/ScratchAddons#2875

```jsonc
// You already have this
"name": "Items",
// You already have this
"id": "items",
// You already have this
"type": "table",
// An array of arrays with 2 strings
// Default values for the rows
"default": [
  ["Create", "/projects/editor/"],
  ["Explore", "/explore/projects/all"],
  ["Ideas", "/ideas"],
  ["About", "/about"]
],
// An array of "settings" excluding setting type "table" excluding default property
// Defines the settings in each row
"row": [
  {
    "name": "Name",
    "id": "name",
    "type": "string"
  },
  {
    "name": "URL",
    "id": "url",
    "type": "string"
  }
],
// Presets for new rows
"presets": [
  {
    "name": "Create",
    "values": ["Create", "/projects/editor/"]
  },
  {
    "name": "Explore",
    "values": ["Explore", "/explore/projects/all"]
  },
  {
    "name": "Ideas",
    "values": ["Ideas", "/ideas"]
  },
  {
    "name": "About",
    "values": ["About", "/about"]
  }
]
```

**Comment by Hans5958** [comment]
Should've linked the issue that is related

Also, I couldn't do and cross-checking between two fields, so the enforcement will be quite lax, but maybe there'll be some JSON-Schema stuff that could make it possible. Maybe.

Maybe I could add the types in the moment. Could you tell me what are the valid types?

**Comment by Hans5958** [comment]
@TheColaber

**Comment by Hans5958** [comment]
At Discord:

> valid types... didn't i have them there?

No? You only gave a string example. There are no other types? Or are the types are the same as the usual setting values? (Sorry for bad English)

**Comment by TheColaber** [comment]
Ah yes, If this were done with a boolean or number input, the type could belong in the default param instead of strings. Everything else should be the right type.

**Comment by Hans5958** [comment]
Never mind. I didn't read the whole code block. I have limited viewpoint on my phone. Sorry.

**Comment by Hans5958** [comment]
Alright, I think I got it working. Before I merge this, could you test it out by adding the `$schema` field in VSCode and see if there are errors? You just need to do it locally, and then you can delete it afterwards. 

```json5
{
    "$schema": "https://raw.githubusercontent.com/ScratchAddons/manifest-schema/table-settings/1/1.12.json", // This one!
    "name": "...",
    ...
}
```

**Comment by TheColaber** [comment]
Looks good, but I can't test, I'm not at my computer now. I'll let you know once I do

**Comment by Hans5958** [comment]
Okay. Just in case this you need this quick, please tell me.

**Comment by TheColaber** [comment]
@Hans5958 Tested, works great, you can merge now or when ScratchAddons/ScratchAddons#2875 gets merged

**Comment by Hans5958** [comment]
Good to know.

Yeah, like usual, merge that then this. Thanks for finally link the issue.

**Comment by TheColaber** [comment]
There is now a new added property, presets, so I've updated my original post.
