### ISSUE TITLE
Remove property: traps

### ISSUE THREAD

**Issue by Hans5958** [ScratchAddons/manifest-schema#41]
Based on ScratchAddons/website-v2#74, it seems that `traps` is going to be deprecated. I'm not sure whether this is already implemented or deprecated or what, so an enlightenment would be appreciated.

cc @TheColaber

**Comment by TheColaber** [comment]
@Hans5958 Actually this has been depreciated for a VERY long time... I think from like v1.4ish? But removing `i10n` was done in the previous version.

**Comment by Hans5958** [comment]
I see. I shall done this quick.
