### ISSUE TITLE
v1.1.0 updates

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/manifest-schema#5]
- Settings of type `color` - not sure if you're validating the default values, if you are, it should be hex.
- `warning` property in the manifest: string, not required.
- `traps` property in the manifest: boolean, not required, soon to be object - but in future versions.

**Comment by Hans5958** [comment]
All implemented, but few notes.
- I assumed color is something like "FFFFFF", not "#FFFFFF".
- `warning` and `traps` still needs description.

**Comment by WorldLanguages** [comment]
@Hans5958 Hex does include a leading "#"
I'll take care of the descriptions

**Comment by Hans5958** [comment]
Ah okay
