### ISSUE TITLE
Setting presets (suggestion)

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/manifest-schema#8]
My suggestion, but changes are accepted because the schema might be complex with this exact way:
- Adding a new property `presets` on root of the manifest. Array of objects, each with a property `id` and `name`.
- Adding a new property `presetsValues` to each `setting` object (each object on the `settings` array). It would be an object, where the key is the ID of the preset, and the value is what that particular setting should be set to if that preset is selected by the user.
I think it should be allowed for a setting to not define its value for a preset. In that case, the default is assumed to be the preset value.

**Comment by Hans5958** [comment]
Could you give me the sample of the manifest?

**Comment by Explosion-Scratch** [comment]
That sounds good!

**Comment by WorldLanguages** [comment]
```json
{
  "presets": [
    {
      "id": "darkMode",
      "name": "Dark mode"
    },
    {
      "id": "lightMode",
      "name": "Light mode"
    }
  ],
  "settings": [
    {
      "id": "theColor",
      "name": "The color",
      "type": "color",
      "default": "#123456",
      "presets": {
        "darkMode": "#000000",
        "lightMode": "#FFFFFF"
      }
    }
  ]
}
```

**Comment by WorldLanguages** [comment]
The `presets` property is optional, specifying every preset in every setting is optional, and the setting value for each preset must respect the setting type.

**Comment by Hans5958** [comment]
Ah okay. Will implement it some time later.

**Comment by WorldLanguages** [comment]
Sounds good. I think I'll be able to have this work for v1.2 but not sure. If so, only one addon will use it so it's not a problem to have a single invalid schema run.

**Comment by WorldLanguages** [comment]
Note:
> I think it should be allowed for a setting to not define its value for a preset. In that case, the default is assumed to be the preset value.

I disagree with my previous statement. I'll make it so settings that do not have a specified preset value, do not have their value changed when the user changes preset. That seems more logical - some themes might have additional settings that shouldn't change if the user chooses a preset.

**Comment by ZenithRogue** [comment]
Linking this issue here: https://github.com/ScratchAddons/ScratchAddons/issues/462

**Comment by ZenithRogue** [comment]
I went ahead and implemented presets in a way that actually makes sense, here is the schema for that update

**Comment by Hans5958** [comment]
Reopening again because there are different ideas on the future implementation. Also, the schema for the presets are removed for now.

aa1b78c67ecb05a456ce372eca6665e50b3b3dbe

**Comment by ZenithRogue** [comment]
@Hans5958 oops, forgot to link the implementation PR here

https://github.com/ScratchAddons/ScratchAddons/pull/563

**Comment by Hans5958** [comment]
Yeah, I'll wait for that PR merged or is going to be merged before I do things here.

**Comment by ZenithRogue** [comment]
@Hans5958 it is merged, and ready for the schema!

**Comment by Hans5958** [comment]
Okay. Will take a look now.

**Comment by Hans5958** [comment]
Hello, an update, and also a warning here.

Due to the implementation of the presets which values are not inside of the settings (aka @ZenithRogue way), there is no way that I could implement a check on this. Instead, it is possible to do this if the preset values are inside the settings (aka @WorldLanguages' way)

**Comment by ZenithRogue** [comment]
Can you make the schema ignore the preset values? Bc this preset method is infinitely cleaner, and allows you to set the values jn a big group, rather than placing the. Individually

**Comment by WorldLanguages** [comment]
@Hans5958 Kinda crazy, but you could make a JS script that converts the Zenith way to the W_L way, then runs the schema against the W_L way :P

**Comment by Hans5958** [comment]
> Can you make the schema ignore the preset values? Bc this preset method is infinitely cleaner, and allows you to set the values in a big group, rather than placing each value individually

What do you mean by ignoring it, if I can't make it work in the first place? This is just a kind warning to check the types since it is not covered by the schema.

> @Hans5958 Kinda crazy, but you could make a JS script that converts the Zenith way to the W_L way, then runs the schema against the W_L way :P

That's not JSON schema works. That would be another test method.
